### ISSUE TITLE
Error on Generating Readings on MacOSX 10.15.5 Catalina

### ISSUE THREAD

**Issue by ozykozy** [jcsirot/anki-simple-furigana#6] opened 2020-07-30 03:05 UTC
Just like the problem issued for 10.15.4, I'm experiencing the same problemn when generating readings.
Ever since the mac is updated, regardless of how many computers I tried, I'm experiencing the error below.
It only pops when I attempt to generate readings. And not when I delete.

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.26 (70784154) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
Platform: Mac 10.15.5
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-07-30 11:47:40
Add-ons possibly involved: ⁨SimpleFurigana⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/oz/Library/Application Support/Anki2/addons21/1444055400/reading.py", line 89, in ensureOpen
    self.mecab = subprocess.Popen(
  File "subprocess.py", line 854, in __init__
  File "subprocess.py", line 1702, in _execute_child
OSError: [Errno 86] Bad CPU type in executable: '/Users/oz/Library/Application Support/Anki2/addons21/1444055400/mecab/mecab'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/oz/Library/Application Support/Anki2/addons21/1444055400/__init__.py", line 266, in <lambda>
    lambda x: self._setHtml(x, callback))
  File "/Users/oz/Library/Application Support/Anki2/addons21/1444055400/__init__.py", line 278, in _setHtml
    callback(self)
  File "/Users/oz/Library/Application Support/Anki2/addons21/1444055400/__init__.py", line 63, in <lambda>
    Selection(editor, lambda s: action(editor, s))
  File "/Users/oz/Library/Application Support/Anki2/addons21/1444055400/__init__.py", line 76, in generateRuby
    html = makeRuby(html)
  File "/Users/oz/Library/Application Support/Anki2/addons21/1444055400/__init__.py", line 107, in makeRuby
    html = mecab.reading(html)
  File "/Users/oz/Library/Application Support/Anki2/addons21/1444055400/reading.py", line 98, in reading
    self.ensureOpen()
  File "/Users/oz/Library/Application Support/Anki2/addons21/1444055400/reading.py", line 94, in ensureOpen
    raise Exception(
Exception: Please ensure your Linux system has 64 bit binary support.

**Comment by qweruiop182** [comment] 2020-08-01 20:10
Hi! I have the same issue and get the same message from Anki since I updated my Mac today.

**Comment by jcsirot** [comment] 2020-09-22 09:05
I was able to reproduce the issue on 10.15.6. I'm going to investigate

**Comment by jcsirot** [comment] 2020-09-27 13:19
Fixed in version 1.0.0 which has been released on AnkiWeb

**Closed by jcsirot** 2020-09-27 13:19 UTC
